-- DROP SCHEMA taskcosttrackerdb IF EXISTS;

-- CREATE SCHEMA taskcosttrackerdb;

-- SET SCHEMA taskcosttrackerdb;

DROP TABLE hibernate_sequence IF EXISTS;
DROP TABLE task_operation IF EXISTS;
DROP TABLE task IF EXISTS;

CREATE TABLE IF NOT EXISTS task
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    description     VARCHAR(255) NOT NULL,
    cost            DECIMAL(10, 2),
    status          VARCHAR(20),
    completion_date DATE
);

DROP INDEX idx_task_description IF EXISTS;

CREATE INDEX idx_task_description ON task (description);

INSERT INTO task (id, description, cost, status, completion_date)
VALUES (1, 'First Task', 100.00, 'COMPLETED', CURRENT_DATE),
       (2, 'Second Task', 100.00, 'COMPLETED', DATE '2024-03-01'),
       (3, 'Third Task', 200.00, 'PROJECT', NULL),
       (4, 'Fourth Task', 150.00, 'IN_PROGRESS', NULL),
       (5, 'Fifth Task', 150.00, 'PROJECT', NULL);

CREATE TABLE IF NOT EXISTS task_operation
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    task_id          BIGINT         NOT NULL,
    description      VARCHAR(255)   NOT NULL,
    planned_quantity BIGINT         NOT NULL,
    actual_quantity  BIGINT,
    price            DECIMAL(10, 2) NOT NULL,
    cost             DECIMAL(10, 2),
    status           VARCHAR(20),
    FOREIGN KEY (task_id) REFERENCES task (id)
);

CREATE TABLE IF NOT EXISTS hibernate_sequence
(
    sequence_name VARCHAR(255) NOT NULL,
    next_val      INT          NOT NULL
);

INSERT INTO hibernate_sequence (sequence_name, next_val)
VALUES ('default', 1);

DROP INDEX idx_task_operation_task_id IF EXISTS;

CREATE INDEX idx_task_operation_task_id ON task_operation (task_id);

INSERT INTO task_operation (id, task_id, description, planned_quantity, actual_quantity, price, cost, status)
VALUES (1, 1, 'Operation', 10, 8, 5.00, 40.00, 'COMPLETED'),
       (2, 2, 'Operation', 15, 15, 4.00, 60.00, 'COMPLETED'),
       (3, 3, 'Operation', 20, 18, 6.00, 108.00, 'PROJECT'),
       (4, 4, 'First Operation', 25, 25, 7.00, 175.00, 'COMPLETED'),
       (5, 4, 'Second Operation', 30, 25, 8.00, 200.00, 'PROJECT'),
       (6, 5, 'First Operation', 35, 30, 9.00, 270.00, 'PROJECT'),
       (7, 5, 'Second Operation', 40, 35, 10.00, 400.00, 'PROJECT'),
       (8, 5, 'Third Operation', 45, 40, 11.00, 495.00, 'PROJECT'),
       (9, 5, 'Fourth Operation', 50, 45, 12.00, 600.00, 'PROJECT'),
       (10, 5, 'Fifth Operation', 55, 50, 13.00, 715.00, 'PROJECT');